{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhoim
spec:
  host: {{ .Values.route.host | default "" | quote }}
  to:
    kind: Service
    name: rhoim
  port:
    targetPort: http
  tls:
    termination: edge
{{- end }}
