apiVersion: v1
kind: Service
metadata: { name: rhoim }
spec:
  selector:
    app: {{ if .Values.singleContainer }}rhoim-appliance{{ else }}rhoim-gateway{{ end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ if .Values.singleContainer }}8080{{ else }}8000{{ end }}
  type: {{ .Values.service.type }}
