# Optional: ServiceMonitor if Prometheus Operator is installed
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhoim
spec:
  selector:
    matchLabels:
      app: {{ if .Values.singleContainer }}rhoim-appliance{{ else }}rhoim-gateway{{ end }}
  endpoints:
  - port: http
    path: /metrics
